### ISSUE TITLE
Pie chart: bug with three data

### ISSUE THREAD

**Issue by okeul** [ffoodd/sseeeedd#71]
See https://codepen.io/okeul/pen/ELzzKg

**Comment by okeul** [comment]
Good catch ;-)

**Comment by ffoodd** [comment]
In fact it works pretty well, I added [an example right in the doc](https://ffoodd.github.io/sseeeedd/graphiques.html). 

Using another `span` doesn't have any drawback, but there's some visual quirk since patterns don't match.

Two ways to improve:
1. switch code pattern for values over 50%: remove `overflow: hidden;`on span should be sufficient.
2. try another way, using `clip-path` and some maths.

Let's try number 1. for now :D

**Comment by ffoodd** [comment]
Ok so right now it's much simpler: when a value is over 50, you'll need to add `.over-50` class on `span` tag.

This works but isn't fully automated, so quite deceptive for now. This is a workaround, but I keep this in mind :)

Is this workaround enough, for you?

**Comment by okeul** [comment]
Thanks ! 

There is still a problem with the hover but it's minor.
<img width="327" alt="" src="https://user-images.githubusercontent.com/6248074/46950469-12d55a00-d085-11e8-98f7-b4a5b3be0a04.png">

https://codepen.io/okeul/pen/ELzzKg

**Comment by ffoodd** [comment]
In fact you defined the `--start` value to 27 for the big part, but the previous part is set to 30 :)
Just use 27 as the first value and it should be good ;)

**Comment by okeul** [comment]
My bad ;-) thanks

**Comment by ffoodd** [comment]
FYI, I'm working (in my spare time, of course) on making pie charts use `clip-path`.

This requires some maths again, since points need to be placed on the circle rather than the square box: running `sin` calculations again and some conditions for CSS variables to place points whether value is greater than 25, 50, and 75…

Maybe a few days more :) But it's doable so I'll do it!

**Comment by ffoodd** [comment]
@okeul If you have a look to the new version of pie charts, using `clip-path` allows any value to work fine :)
However support is downgraded: no Edge, for now…

Cross-browser testing needs to be done (and I'll update documentation accordingly when it's done).
